In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import numpy as np
virus = 'influenza'
with open('/content/gdrive/My Drive/KTH ÅR 4/P3/Comp Bio/Data/' + virus +'_knn_graph_shuffled.npy', 'rb') as f:
    knn_graph = np.load(f)

In [ ]:
!pip install scikit-network

     |████████████████████████████████| 8.4MB 5.7MB/s 
     |████████████████████████████████| 27.4MB 165kB/s 
     |████████████████████████████████| 15.3MB 36.3MB/s 
ERROR: tensorflow 2.4.1 has requirement numpy~=1.19.2, but you'll have numpy 1.20.2 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1


In [ ]:
from sknetwork.clustering import Louvain

print(knn_graph.shape)

louvain = Louvain()
labels1 = louvain.fit_transform(knn_graph)

print(labels1)

print(set(labels1))


first = []
second = []
for idx,i in enumerate(labels1):
  if i == 0:
    first.append(idx)
  else:
    second.append(idx)

print(len(first))
print(len(second))

(1500, 1500)
[0 0 0 ... 0 0 0]
{0, 1}
1489
11


In [ ]:
virus = 'influenza'
with open('/content/gdrive/My Drive/KTH ÅR 4/P3/Comp Bio/Data/' + virus +'_knn_graph_unshuffled.npy', 'rb') as f:
    knn_graph = np.load(f)

In [ ]:
from sknetwork.clustering import Louvain

print(knn_graph.shape)

louvain = Louvain()
labels2 = louvain.fit_transform(knn_graph)

print(labels2)

print(set(labels2))


first = []
second = []
for idx,i in enumerate(labels2):
  if i == 0:
    first.append(idx)
  else:
    second.append(idx)

print(len(first))
print(len(second))

(1500, 1500)
[0 0 0 ... 0 0 0]
{0, 1}
1489
11


In [ ]:
labels1==labels2


array([ True,  True,  True, ...,  True,  True,  True])